#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{ $serviceMeshEnabled := include "eric-lcm-git-repository.serviceMesh.enabled" .}}
{{- $global := fromYaml (include "eric-lcm-git-repository.global" .) }}

{{- if eq $serviceMeshEnabled "true" -}}

apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "eric-lcm-git-repository.name" . }}-destinationrule
  labels:
    {{- include "eric-lcm-git-repository.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-lcm-git-repository.annotations" . | nindent 4 }}
spec:
  host: {{ include "eric-lcm-git-repository.name" . }}
  exportTo:
  - "."
  {{- if $global.security.tls.enabled }}
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  {{- else }}
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
  {{- end }}
{{- end -}}
