#
# COPYRIGHT Ericsson 2022
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{ if eq (include "eric-lcm-git-repository.serviceMesh.enabled" .) "true" -}}
{{- $global := fromYaml (include "eric-lcm-git-repository.global" .) }}
{{- if $global.security.tls.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: {{ include "eric-lcm-git-repository.name" . }}-ef-pg
  labels:
    {{- include "eric-lcm-git-repository.labels" . | nindent 4 }}
  annotations:
     {{- include "eric-lcm-git-repository.annotations" . | nindent 4 }}
spec:
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        context: SIDECAR_OUTBOUND
        listener:
          portNumber: {{ include "eric-lcm-git-repository.getDatabasePort" . }}
          filterChain:
            filter:
              name: "envoy.filters.network.tcp_proxy"
      patch:
        operation: INSERT_BEFORE
        value:
          name: "envoy.filters.network.postgres_proxy"
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.postgres_proxy.v3alpha.PostgresProxy
            stat_prefix: postgres
            upstream_ssl: REQUIRE
    - applyTo: CLUSTER
      match:
        cluster:
          portNumber: {{ include "eric-lcm-git-repository.getDatabasePort" . }}
          service: {{ .Values.serviceMesh.egress.documentdatabasepg.serviceName }}.{{ .Release.Namespace }}.svc.cluster.local
        context: SIDECAR_OUTBOUND
      patch:
        operation: MERGE
        value:
          transport_socket:
            name: envoy.transport_sockets.starttls
            typed_config:
              '@type': type.googleapis.com/envoy.extensions.transport_sockets.starttls.v3.UpstreamStartTlsConfig
              tls_socket_config:
                allow_renegotiation: true
                common_tls_context:
                  tls_certificate_sds_secret_configs:
                    - name: {{ include "eric-lcm-git-repository.tls-certificate-secret" . | squote}}
                      sds_config:
                        api_config_source:
                          api_type: GRPC
                          transport_api_version: V3
                          grpc_services:
                            - envoy_grpc:
                                cluster_name: sds-grpc
                          set_node_on_first_message_only: true
                        resource_api_version: V3
                  combined_validation_context:
                    default_validation_context: {}
                    validation_context_sds_secret_config:
                      name: {{ include "eric-lcm-git-repository.tls-validation-secret" . | squote}}
                      sds_config:
                        api_config_source:
                          api_type: GRPC
                          transport_api_version: V3
                          grpc_services:
                            - envoy_grpc:
                                cluster_name: sds-grpc
                          set_node_on_first_message_only: true
                        resource_api_version: V3
  workloadSelector:
    labels:
      {{- include "eric-lcm-git-repository.labels" . | nindent 6 }}
{{- end }}
{{- end }}
