
{{ if .Values.initConfig.enabled -}}
{{- $secretname := .Values.gitea.config.redis.serviceUser.secret.name }}
{{- $secret := lookup "v1" "Secret" .Release.Namespace $secretname }}
{{- if not $secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.gitea.config.redis.serviceUser.secret.name | quote }}
  labels:
    {{- include "eric-lcm-git-repository.labels" . | nindent 4 }}
  annotations:
    {{- $commonAnn := include "eric-lcm-git-repository.annotations" . | fromYaml }}
    {{- $hookAnn := dict -}}
    {{- $_ := set $hookAnn "helm.sh/hook" "pre-install,pre-upgrade" -}}
    {{- $_ := set $hookAnn "helm.sh/hook-delete-policy" "before-hook-creation" -}}
    {{- $_ := set $hookAnn "helm.sh/hook-weight" "2" -}}
    {{- include "eric-lcm-git-repository.mergeAnnotations" (dict "location" (.Template.Name) "sources" (list $commonAnn $hookAnn)) | trim | nindent 4 }}
type: Opaque
data:
{{- include "eric-lcm-git-repository.init-config-redis-serviceuser-secret" . | nindent 2 }}
{{- end -}}
{{- end }}
