{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eric-lcm-git-repository.serviceAccountName" . | quote }}
  labels: {{ include "eric-lcm-git-repository.labels" . | nindent 4 }}
  annotations: {{ include "eric-lcm-git-repository.annotations" . | nindent 4 }}
automountServiceAccountToken: false
{{- end -}}
