#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#


{{ if .Values.initConfig.enabled -}}
{{- $global := fromYaml ( include "eric-lcm-git-repository.global" . ) -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "eric-lcm-git-repository.init-config-job-name" . | quote }}
  labels:
    {{- include "eric-lcm-git-repository.labels" . | nindent 4 }}
  annotations:
    {{- $commonAnn := include "eric-lcm-git-repository.annotations" . | fromYaml }}
    {{- $hookAnn := dict -}}
    {{- $_ := set $hookAnn "helm.sh/hook" "pre-install,pre-upgrade" -}}
    {{- $_ := set $hookAnn "helm.sh/hook-delete-policy" "before-hook-creation" -}}
    {{- $_ := set $hookAnn "helm.sh/hook-weight" (.Values.initConfig.hookWeightInitJob | toString) -}}
    {{- include "eric-lcm-git-repository.mergeAnnotations" (dict "location" (.Template.Name) "sources" (list $commonAnn $hookAnn)) | trim | nindent 4 }}
spec:
  completions: 1
  parallelism: 1
  backoffLimit: {{ .Values.initConfig.jobBackOffLimit }}
  template:
    metadata:
      labels:
        {{- include "eric-lcm-git-repository.labels" . | nindent 8 }}
        "sidecar.istio.io/inject": "false"
      annotations:
        {{- $commonAnnotations := include "eric-lcm-git-repository.annotations" . | fromYaml }}
        {{- $appArmorNotation := include "eric-lcm-git-repository.appArmorAnnotationsInitializer" . | fromYaml -}}
        {{- include "eric-lcm-git-repository.mergeAnnotations" (dict "location" (.Template.Name) "sources" (list $commonAnnotations $appArmorNotation)) | trim | nindent 8 }}
    spec:
      {{- if include "eric-lcm-git-repository.pullSecret" . }}
      imagePullSecrets:
        - name: {{ include "eric-lcm-git-repository.pullSecret" . | quote}}
      {{- end }}
      serviceAccountName: {{ include "eric-lcm-git-repository.init-config-sa-name" . | quote }}
      securityContext:
        fsGroup: {{ include "eric-lcm-git-repository.fsGroup.coordinated" . }}
        {{ include "eric-lcm-git-repository.seccomp-profile" (dict "Values" .Values "Scope" "Pod") | nindent 8 }}
      {{- include "eric-lcm-git-repository.podPriorityClass" . | nindent 6 }}
      containers:
        {{- include "eric-lcm-git-repository.initializerContainerSpec" . | nindent 8 }}
      volumes:
        {{- include "eric-lcm-git-repository.initializerVolumes" . | nindent 8 }}   
      nodeSelector: {{ include  "eric-lcm-git-repository.nodeSelector" . | nindent 8 }}
{{ if or ($global.tolerations) (.Values.tolerations) }}
      tolerations: {{ include "eric-lcm-git-repository.merge-tolerations" . | nindent 8 }}
{{ end }}
      topologySpreadConstraints: {{ toYaml .Values.topologySpreadConstraints | nindent 8 }}
      {{- include "eric-lcm-git-repository.affinityPodAntiAffinity" . | indent 6 }} 
      restartPolicy: OnFailure 
{{- end -}}

