#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#


{{ if .Values.initConfig.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eric-lcm-git-repository.init-config-sa-name" . | quote }}
  labels:
    {{- include "eric-lcm-git-repository.labels" . | nindent 4 }}
  annotations:
    {{- $commonAnn := include "eric-lcm-git-repository.annotations" . | fromYaml }}
    {{- $hookAnn := dict -}}
    {{- $_ := set $hookAnn "helm.sh/hook" "pre-install,pre-upgrade" -}}
    {{- $_ := set $hookAnn "helm.sh/hook-delete-policy" "before-hook-creation" -}}
    {{- $_ := set $hookAnn "helm.sh/hook-weight" (.Values.initConfig.hookWeightInitResources | toString) -}}
    {{- include "eric-lcm-git-repository.mergeAnnotations" (dict "location" (.Template.Name) "sources" (list $commonAnn $hookAnn)) | trim | nindent 4 }}
{{- end }}