{{ if .Values.initConfig.enabled -}}
{{- $secretname := .Values.gitea.admin.secret }}
{{- $secret := lookup "v1" "Secret" .Release.Namespace $secretname }}
{{- if not $secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.gitea.admin.secret  | quote }}
  labels:
    {{- include "eric-lcm-git-repository.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-lcm-git-repository.annotations" . | nindent 4 }}
type: Opaque
data:
{{- include "eric-lcm-git-repository.init-config-gitea-admincreds-secret" . | nindent 2 }}
{{- end -}}
{{- end -}}
