#
# COPYRIGHT Ericsson 2024
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

modelVersion: '3.0'
2pp_dependencies:
- name: Common Base OS Micro Image
  version: 6.14.0
  abc_number: CXC2012032
  evms:
    register: 'yes'
  category: ''
- name: Stdout Redirect
  version: 1.36.0
  abc_number: CXA30176
  evms:
    register: 'yes'
  category: ''
dependencies: []

